#!/usr/bin/env node

var exec = require('child_process').exec;
var spawn = require('child_process').spawn;
var fs = require('fs');
var url = require('url');
var http = require('http');
var zlib=require("zlib");
//var addon_sdk=fs.createWriteStream("addon-sdk");

console.log("Installing development environment");

var DOWNLOAD_URL="http://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/jetpack-sdk-latest.tar.gz";

var wget="wget "+DOWNLOAD_URL;

console.log("Downloading Addon SDK");
var child=exec(wget,function(err,stdout,stderr){
	if(err){
		process.exit(1);
	}else{
		console.log("Extracting GZip");
		//fs.createReadStream("jetpack-sdk-latest.tar.gz").pipe(zlib.createGunzip()).pipe(addon_sdk);
		var tar="tar xzvf jetpack-sdk-latest.tar.gz";
		exec(tar,function(err,stdout,stderr){
			if(err){
				process.exit(1);
			}else{
				console.log("Renaming folders");
				exec("mv addon-sdk-* addon-sdk",function(err,stdout,stderr){
					if(err){
						process.exit(1);
					}else{
						process.exit(0);
					}
				});	
			}
		});
	}
}); 


